compressionLevel: 0

enableGlobalCache: false

enableScripts: false

enableTelemetry: false

logFilters:
  - code: YN0076
    level: discard
  - code: YN0013
    level: discard
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard

nmMode: hardlinks-local

nodeLinker: node-modules

packageExtensions:
  "tailwindcss@*":
    dependencies:
      postcss: "*"
      autoprefixer: "*"
