[build]
builder = "nixpacks"

[deploy]
startCommand = "yarn workspace @peas/web start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[deploy.envs]
NODE_ENV = "production" 