-- Add new enum values to ParseStatus
ALTER TYPE "ParseStatus" ADD VALUE 'AWAITING_PARSING';
ALTER TYPE "ParseStatus" ADD VALUE 'COMPLETED_WITH_ERROR';
ALTER TYPE "ParseStatus" ADD VALUE 'COMPLETED_SUCCESSFULLY'; 